// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface Metadata {
    __metadata: {
        modelName: string;
        urlPath?: string;
    };
}

export interface IBackgroundImage extends Metadata {
    /** Image */
    url?: Asset | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** Background size */
    backgroundSize?: 'auto' | 'cover' | 'contain' | undefined;

    /** Background position */
    backgroundPosition?: 'bottom' | 'center' | 'left' | 'left-bottom' | 'left-top' | 'right' | 'right-bottom' | 'right-top' | 'top' | undefined;

    /** Background repeat */
    backgroundRepeat?: 'repeat' | 'repeat-x' | 'repeat-y' | 'no-repeat' | undefined;

    /** Opacity */
    opacity?: number | undefined;
}


export interface IBadge extends Metadata {
    /** Label */
    label: string;

    /** Color */
    color?: 'text-dark' | 'text-light' | 'text-neutral' | 'text-primary' | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IButton extends Metadata {
    /** Label */
    label?: string | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** URL */
    url: string;

    /** Show icon */
    showIcon?: boolean | undefined;

    /** Icon */
    icon?:
        | 'arrowDown'
        | 'arrowLeft'
        | 'arrowRight'
        | 'arrowUp'
        | 'chevronDown'
        | 'chevronLeft'
        | 'chevronBigLeft'
        | 'chevronRight'
        | 'chevronBigRight'
        | 'chevronUp'
        | 'facebook'
        | 'github'
        | 'instagram'
        | 'linkedin'
        | 'mail'
        | 'play'
        | 'reddit'
        | 'send'
        | 'shoppingBag'
        | 'twitter'
        | 'vimeo'
        | 'youtube'
        | undefined;

    /** Icon position */
    iconPosition?: 'left' | 'right' | undefined;

    /** Style */
    style?: 'primary' | 'secondary' | undefined;

    /** Element ID */
    elementId?: string | undefined;
}


export interface ICarouselSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Items */
    items?: IFeaturedItem[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Arrangement */
    variant?: 'next-prev-nav' | 'dots-nav' | 'tabs-nav' | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface ICheckboxFormControl extends Metadata {
    /** Name */
    name: string;

    /** Label */
    label?: string | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface IConfig extends Metadata {
    /** Favicon */
    favicon?: Asset | undefined;

    /** Header configuration */
    header?: IHeader | undefined;

    /** Footer configuration */
    footer?: IFooter | undefined;

    /** Suffix for page titles */
    titleSuffix?: string | undefined;

    /** Default image for social sharing */
    defaultSocialImage?: Asset | undefined;

    /** Default additional meta tags */
    defaultMetaTags?: IMetaTag[] | undefined;
}


export interface IDividerSection extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IEmailFormControl extends Metadata {
    /** Name */
    name?: string | undefined;

    /** Label */
    label?: string | undefined;

    /** Hide label */
    hideLabel?: boolean | undefined;

    /** Placeholder text */
    placeholder?: string | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface IFeaturedItem extends Metadata {
    /** Title */
    title: string;

    /** Tagline */
    tagline?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Image */
    image?: IImageBlock | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-neutralAlt-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFeaturedItemsSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Items */
    items?: IFeaturedItem[] | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Arrangement */
    variant?: 'two-col-grid' | 'three-col-grid' | 'small-list' | 'big-list' | 'toggle-list' | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFeaturedPeopleSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** People */
    people?: IPerson[] | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Arrangement */
    variant?: 'three-col-grid' | 'four-col-grid' | 'mixed-grid' | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFeaturedPostsSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Posts */
    posts?: IPostLayout[] | undefined;

    /** Show post thumbnail */
    showThumbnail?: boolean | undefined;

    /** Show post excerpt */
    showExcerpt?: boolean | undefined;

    /** Show post date */
    showDate?: boolean | undefined;

    /** Show post author */
    showAuthor?: boolean | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Arrangement */
    variant?: 'two-col-grid' | 'three-col-grid' | 'small-list' | 'big-list' | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFooter extends Metadata {
    /** Logo */
    logo?: IImageBlock | undefined;

    /** Title */
    title?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Primary Links */
    primaryLinks?: IFooterLinksGroup | undefined;

    /** Secondary Links */
    secondaryLinks?: IFooterLinksGroup | undefined;

    /** Social links */
    socialLinks?: ISocial[] | undefined;

    /** Legal links */
    legalLinks?: ILink[] | undefined;

    /** Copyright text */
    copyrightText?: string | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFooterLinksGroup extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Links */
    links?: (IButton | ILink)[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFormBlock extends Metadata {
    /** Fields */
    fields?: (ITextFormControl | IEmailFormControl | ITextareaFormControl | ICheckboxFormControl | ISelectFormControl)[] | undefined;

    /** Submit button */
    submitButton?: ISubmitButtonFormControl | undefined;

    /** Action (form submission URL) */
    action?: string | undefined;

    /** Destination (email to redirect responses) */
    destination?: string | undefined;

    /** Element ID */
    elementId: string;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IGenericSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Media */
    media?: IFormBlock | IImageBlock | IVideoBlock | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;

    /** Variants */
    nt_variants?: IGenericSection[] | undefined;

    /** Audience */
    nt_audience?: INtAudience | undefined;
}


export interface IHeader extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Logo */
    logo?: IImageBlock | undefined;

    /** Primary links */
    primaryLinks?: (IButton | ILink | ISubNav)[] | undefined;

    /** Secondary links */
    secondaryLinks?: (IButton | ILink)[] | undefined;

    /** Arrangement */
    variant?:
        | 'logo-left-primary-nav-left'
        | 'logo-left-primary-nav-centered'
        | 'logo-left-primary-nav-right'
        | 'logo-centered-primary-nav-left'
        | 'logo-centered-primary-nav-centered'
        | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IImageBlock extends Metadata {
    /** Image */
    url?: Asset | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IImageGallerySection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Images */
    images?: IImageBlock[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Motion */
    motion?: 'static' | 'move-to-left' | 'move-to-right' | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface ILink extends Metadata {
    /** Label */
    label?: string | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** URL */
    url: string;

    /** Show icon */
    showIcon?: boolean | undefined;

    /** Icon */
    icon?:
        | 'arrowDown'
        | 'arrowLeft'
        | 'arrowRight'
        | 'arrowUp'
        | 'chevronDown'
        | 'chevronLeft'
        | 'chevronBigLeft'
        | 'chevronRight'
        | 'chevronBigRight'
        | 'chevronUp'
        | 'facebook'
        | 'github'
        | 'instagram'
        | 'linkedin'
        | 'mail'
        | 'play'
        | 'reddit'
        | 'send'
        | 'shoppingBag'
        | 'twitter'
        | 'vimeo'
        | 'youtube'
        | undefined;

    /** Icon position */
    iconPosition?: 'left' | 'right' | undefined;

    /** Style */
    style?: 'primary' | 'secondary' | undefined;

    /** Element ID */
    elementId?: string | undefined;
}


export interface IMetaTag extends Metadata {
    /** Property */
    property?:
        | 'og:title'
        | 'og:type'
        | 'og:image'
        | 'og:image:alt'
        | 'og:url'
        | 'og:description'
        | 'og:locale'
        | 'og:site_name'
        | 'og:video'
        | 'twitter:card'
        | 'twitter:site'
        | 'twitter:creator'
        | 'twitter:description'
        | 'twitter:title'
        | 'twitter:image'
        | 'twitter:image:alt'
        | 'twitter:player'
        | undefined;

    /** Content */
    content?: string | undefined;
}


export interface INtAudience extends Metadata {
    /** Name */
    nt_name: string;

    /** Description */
    nt_description?: string | undefined;

    /** Rules */
    nt_rules: Record<string, any>;

    /** Audience Id */
    nt_audience_id: string;
}

/** Ninetailed Audience */


export interface INtMergetag extends Metadata {
    /** Name */
    nt_name: string;

    /** Fallback */
    nt_fallback?: string | undefined;

    /** Merge Tag Id */
    nt_mergetag_id: string;
}

/** Ninetailed Merge Tag */


export interface IPagedPostsSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Show post thumbnail */
    showThumbnail?: boolean | undefined;

    /** Show post excerpt */
    showExcerpt?: boolean | undefined;

    /** Show post date */
    showDate?: boolean | undefined;

    /** Show post author */
    showAuthor?: boolean | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Arrangement */
    variant?: 'two-col-grid' | 'three-col-grid' | 'small-list' | 'big-list' | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IPageLayout extends Metadata {
    /** Title */
    title: string;

    /** Slug */
    slug: string;

    /** Sections */
    sections?:
        | (
              | ICarouselSection
              | IDividerSection
              | IFeaturedItemsSection
              | IFeaturedPeopleSection
              | IFeaturedPostsSection
              | IGenericSection
              | IImageGallerySection
              | IPricingSection
              | IRecentPostsSection
          )[]
        | undefined;

    /** Draft */
    isDraft?: boolean | undefined;

    /** SEO */
    seo?: ISeo | undefined;
}


export interface IPerson extends Metadata {
    /** Name */
    name: string;

    /** Role */
    role?: string | undefined;

    /** Bio */
    bio?: string | undefined;

    /** Image */
    image?: IImageBlock | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-neutralAlt-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IPostFeedLayout extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Slug */
    slug: string;

    /** Post feed */
    postFeed?: IPagedPostsSection | undefined;

    /** Number of posts per page */
    numOfPostsPerPage?: number | undefined;

    /** Enable search */
    enableSearch?: boolean | undefined;

    /** Top sections */
    topSections?:
        | (
              | ICarouselSection
              | IDividerSection
              | IFeaturedItemsSection
              | IFeaturedPeopleSection
              | IFeaturedPostsSection
              | IGenericSection
              | IImageGallerySection
              | IPricingSection
              | IRecentPostsSection
          )[]
        | undefined;

    /** Bottom sections */
    bottomSections?:
        | (
              | ICarouselSection
              | IDividerSection
              | IFeaturedItemsSection
              | IFeaturedPeopleSection
              | IFeaturedPostsSection
              | IGenericSection
              | IImageGallerySection
              | IPricingSection
              | IRecentPostsSection
          )[]
        | undefined;

    /** Draft */
    isDraft?: boolean | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;

    /** SEO */
    seo?: ISeo | undefined;
}


export interface IPostFeedSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Show post thumbnail */
    showThumbnail?: boolean | undefined;

    /** Show post excerpt */
    showExcerpt?: boolean | undefined;

    /** Show post date */
    showDate?: boolean | undefined;

    /** Show post author */
    showAuthor?: boolean | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Arrangement */
    variant?: 'two-col-grid' | 'three-col-grid' | 'small-list' | 'big-list' | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IPostLayout extends Metadata {
    /** Title */
    title: string;

    /** Slug */
    slug: string;

    /** Date */
    date: string;

    /** Author */
    author?: IPerson | undefined;

    /** Excerpt */
    excerpt?: string | undefined;

    /** Featured image */
    featuredImage?: IImageBlock | undefined;

    /** Content */
    content?: string | undefined;

    /** Sections */
    bottomSections?:
        | (
              | ICarouselSection
              | IDividerSection
              | IFeaturedItemsSection
              | IFeaturedPeopleSection
              | IFeaturedPostsSection
              | IGenericSection
              | IImageGallerySection
              | IPricingSection
              | IRecentPostsSection
          )[]
        | undefined;

    /** Exclude from blog feed */
    isFeatured?: boolean | undefined;

    /** Draft */
    isDraft?: boolean | undefined;

    /** SEO */
    seo?: ISeo | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-neutralAlt-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IPricingPlan extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Price */
    price?: string | undefined;

    /** Details */
    details?: string | undefined;

    /** Description */
    description?: string | undefined;

    /** Features */
    features?: string[] | undefined;

    /** Image */
    image?: IImageBlock | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-neutralAlt-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IPricingSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Plans */
    plans?: IPricingPlan[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IRecentPostsSection extends Metadata {
    /** Title */
    title?: ITitleBlock | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Number of recent posts to show */
    recentCount?: number | undefined;

    /** Show post thumbnail */
    showThumbnail?: boolean | undefined;

    /** Show post excerpt */
    showExcerpt?: boolean | undefined;

    /** Show post date */
    showDate?: boolean | undefined;

    /** Show post author */
    showAuthor?: boolean | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Arrangement */
    variant?: 'two-col-grid' | 'three-col-grid' | 'small-list' | 'big-list' | undefined;

    /** Colors */
    colors?: 'bg-light-fg-dark' | 'bg-neutral-fg-dark' | 'bg-dark-fg-light' | undefined;

    /** Background image */
    backgroundImage?: IBackgroundImage | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface ISelectFormControl extends Metadata {
    /** Name */
    name: string;

    /** Label */
    label?: string | undefined;

    /** Hide label */
    hideLabel?: boolean | undefined;

    /** Default value */
    defaultValue?: string | undefined;

    /** Options */
    options?: string[] | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface ISeo extends Metadata {
    /** Title meta tag (overrides title) */
    metaTitle?: string | undefined;

    /** Description meta tag */
    metaDescription?: string | undefined;

    /** Add title suffix */
    addTitleSuffix?: boolean | undefined;

    /**  Image for social sharing */
    socialImage?: Asset | undefined;

    /** Additional meta tags */
    metaTags?: IMetaTag[] | undefined;
}


export interface ISocial extends Metadata {
    /** Alt text */
    altText?: string | undefined;

    /** URL */
    url: string;

    /** Icon */
    icon: 'facebook' | 'github' | 'instagram' | 'linkedin' | 'mail' | 'reddit' | 'twitter' | 'vimeo' | 'youtube';

    /** Element ID */
    elementId?: string | undefined;
}


export interface ISubmitButtonFormControl extends Metadata {
    /** Label */
    label?: string | undefined;

    /** Show icon */
    showIcon?: boolean | undefined;

    /** Icon */
    icon?:
        | 'arrowDown'
        | 'arrowLeft'
        | 'arrowRight'
        | 'arrowUp'
        | 'chevronDown'
        | 'chevronLeft'
        | 'chevronBigLeft'
        | 'chevronRight'
        | 'chevronBigRight'
        | 'chevronUp'
        | 'facebook'
        | 'github'
        | 'instagram'
        | 'linkedin'
        | 'mail'
        | 'play'
        | 'reddit'
        | 'send'
        | 'shoppingBag'
        | 'twitter'
        | 'vimeo'
        | 'youtube'
        | undefined;

    /** Icon position */
    iconPosition?: 'left' | 'right' | undefined;

    /** Style */
    style?: 'primary' | 'secondary' | undefined;

    /** Element ID */
    elementId?: string | undefined;
}


export interface ISubNav extends Metadata {
    /** Label */
    label?: string | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** Links */
    links?: ILink[] | undefined;

    /** Label style */
    labelStyle?: 'primary' | 'secondary' | undefined;
}


export interface ITextareaFormControl extends Metadata {
    /** Name */
    name: string;

    /** Label */
    label?: string | undefined;

    /** Hide label */
    hideLabel?: boolean | undefined;

    /** Placeholder text */
    placeholder?: string | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface ITextFormControl extends Metadata {
    /** Name */
    name: string;

    /** Label */
    label?: string | undefined;

    /** Hide label */
    hideLabel?: boolean | undefined;

    /** Placeholder text */
    placeholder?: string | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface IThemeStyle extends Metadata {
    /** Light */
    light?: string | undefined;

    /** Dark */
    dark?: string | undefined;

    /** Neutral */
    neutral?: string | undefined;

    /** Neutral alt */
    neutralAlt?: string | undefined;

    /** Primary */
    primary?: string | undefined;

    /** Font - body & captions */
    fontBody?: 'sans' | 'serif' | undefined;

    /** Font - headlines & subtitles */
    fontHeadlines?: 'sans' | 'serif' | undefined;

    /** H1 */
    h1?: IThemeStyleHeading | undefined;

    /** H2 */
    h2?: IThemeStyleHeading | undefined;

    /** H3 */
    h3?: IThemeStyleHeading | undefined;

    /** H4 */
    h4?: IThemeStyleHeading | undefined;

    /** H5 */
    h5?: IThemeStyleHeading | undefined;

    /** H6 */
    h6?: IThemeStyleHeading | undefined;

    /** Primary button */
    buttonPrimary?: IThemeStyleButton | undefined;

    /** Secondary button */
    buttonSecondary?: IThemeStyleButton | undefined;

    /** Primary link */
    linkPrimary?: IThemeStyleLink | undefined;

    /** Secondary link */
    linkSecondary?: IThemeStyleLink | undefined;
}


export interface IThemeStyleButton extends Metadata {
    /** Font weight */
    weight?: 'normal' | 'medium' | 'bold' | undefined;

    /** Case */
    case?: 'none' | 'lowercase' | 'capitalize' | 'uppercase' | undefined;

    /** Letter spacing */
    letterSpacing?: 'tighter' | 'tight' | 'normal' | 'wide' | 'wider' | undefined;

    /** Corner radius */
    borderRadius?: 'none' | 'DEFAULT' | 'lg' | 'xl' | 'full' | undefined;

    /** Shadow */
    shadow?: 'none' | 'md' | 'xl' | undefined;

    /** Horizontal padding */
    horizontalPadding?: number | undefined;

    /** Vertical padding */
    verticalPadding?: number | undefined;
}


export interface IThemeStyleHeading extends Metadata {
    /** Font size */
    size?: 'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl' | '6xl' | '7xl' | '8xl' | '9xl' | undefined;

    /** Font weight */
    weight?: 'normal' | 'medium' | 'bold' | undefined;

    /** Decoration */
    decoration?: 'none' | 'underline' | 'line-through' | undefined;

    /** Case */
    case?: 'none' | 'lowercase' | 'capitalize' | 'uppercase' | undefined;

    /** Letter spacing */
    letterSpacing?: 'tighter' | 'tight' | 'normal' | 'wide' | 'wider' | undefined;
}


export interface IThemeStyleLink extends Metadata {
    /** Font weight */
    weight?: 'normal' | 'medium' | 'bold' | undefined;

    /** Case */
    case?: 'none' | 'lowercase' | 'capitalize' | 'uppercase' | undefined;

    /** Letter spacing */
    letterSpacing?: 'tighter' | 'tight' | 'normal' | 'wide' | 'wider' | undefined;
}


export interface ITitleBlock extends Metadata {
    /** Text */
    text?: string | undefined;

    /** Color */
    color?: 'text-dark' | 'text-light' | 'text-neutral' | 'text-primary' | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IVideoBlock extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Video URL (YouTube, Vimeo, .mp4) */
    url?: string | undefined;

    /** Autoplay */
    autoplay?: boolean | undefined;

    /** Loop */
    loop?: boolean | undefined;

    /** Muted */
    muted?: boolean | undefined;

    /** Controls */
    controls?: boolean | undefined;

    /** Aspect ratio */
    aspectRatio?: '4:3' | '16:9' | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export type CONTENT_TYPE =
    | 'BackgroundImage'
    | 'Badge'
    | 'Button'
    | 'CarouselSection'
    | 'CheckboxFormControl'
    | 'Config'
    | 'DividerSection'
    | 'EmailFormControl'
    | 'FeaturedItem'
    | 'FeaturedItemsSection'
    | 'FeaturedPeopleSection'
    | 'FeaturedPostsSection'
    | 'Footer'
    | 'FooterLinksGroup'
    | 'FormBlock'
    | 'GenericSection'
    | 'Header'
    | 'ImageBlock'
    | 'ImageGallerySection'
    | 'Link'
    | 'MetaTag'
    | 'nt_audience'
    | 'nt_mergetag'
    | 'PagedPostsSection'
    | 'PageLayout'
    | 'Person'
    | 'PostFeedLayout'
    | 'PostFeedSection'
    | 'PostLayout'
    | 'PricingPlan'
    | 'PricingSection'
    | 'RecentPostsSection'
    | 'SelectFormControl'
    | 'Seo'
    | 'Social'
    | 'SubmitButtonFormControl'
    | 'SubNav'
    | 'TextareaFormControl'
    | 'TextFormControl'
    | 'ThemeStyle'
    | 'ThemeStyleButton'
    | 'ThemeStyleHeading'
    | 'ThemeStyleLink'
    | 'TitleBlock'
    | 'VideoBlock';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
